backend = "xrender";
experimental-backends = true;
unredir-if-possible = false;
vsync = false;
refresh-rate = 0;

blur-background-frame = false;
blur-background-fixed = false;
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

shadow = true;
shadow-opacity = 0.2;
shadow-radius = 0;
shadow-offset-x = 3;
shadow-offset-y = 3;
shadow-ignore-shaped = false;
shadow-exclude = [
  "class_g = 'Telegram' && argb",
  "class_g = 'Firefox' && argb",
  "class_g = 'Iceweasel' && argb",
  "name = 'Screenshot'",
  "class_g = 'slop'",
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "x = 0 && y = 0 && override_redirect = true"
]

fading = true;
fade-delta = 1;
no-fading-openclose = true;

wintypes:
 {
   tooltip =
   {
     fade = false;
     shadow = false;
     opacity = 0.90;
     focus = true;
 };
 utility = { shadow = false; };
};
