set showmode
set fileencoding=utf-8

set tags+=.tags
set tags+=.git/tags
set tags+=.git/tags-deps

set nolist
set hlsearch

set noswapfile
set nobackup
set nowb

silent !mkdir ~/.vim/backups > /dev/null 2>&1
set undodir=~/.vim/backups
set undofile

set wildmenu wildoptions=pum
set wildmode=list:longest
set wildignore=*.o,*.obj,*~
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=vendor/assets/**
set wildignore+=*.gem
set wildignore+=.tags
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=node_modules/**
set wildignore+=target/**

set winwidth=84

set nowrap
set linebreak

set laststatus=0
set colorcolumn=0

let g:rustfmt_autosave = 1

let g:go_fmt_command = "goimports"
let g:go_fmt_autosave = 1

let g:scala_sort_across_groups = 1
let g:scala_scaladoc_indent = 1

let g:markdown_minlines = 100
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'ruby', 'scala', 'go']

autocmd BufNewFile,BufReadPost *.md set filetype=markdown

syn match UrlNoSpell "\w\+:\/\/[^[:space:]]\+" contains=@NoSpell
syn match AcronymNoSpell '\<\(\u\|\d\)\{3,}s\?\>' contains=@NoSpell

set t_Co=256

let s:appearance = substitute(system('defaults read -g AppleInterfaceStyle 2>/dev/null'), '\n', '', 'g')
if s:appearance == 'Dark'
  set background=dark
else
  set background=light
endif

colorscheme marques-de-itu
