" ################
" General settings
" ################

" Show current mode down the bottom
set showmode

" The encoding written to file
set fileencoding=utf-8

" Tags
set tags+=.tags
set tags+=.git/tags
set tags+=.git/tags-deps

" ################
" Editing settings
" ################
set list
set hlsearch

" Disable swap files and things like that
set noswapfile
set nobackup
set nowb

" Persistent undo
silent !mkdir ~/.vim/backups > /dev/null 2>&1
set undodir=~/.vim/backups
set undofile

" Completion
set wildmenu
set wildmode=list:longest
set wildignore=*.o,*.obj,*~
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=vendor/assets/**
set wildignore+=*.gem
set wildignore+=.tags
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=node_modules/**
set wildignore+=target/**

" Set min-width of buffer, very useful when spliting panes
set winwidth=84

" Wrap lines is for fools
set nowrap
set linebreak

" ###################
" Appearence settings
" ###################

let base16colorspace=256
set t_Co=256
set background=dark
colorscheme base16-grayscale-dark

augroup color_tweaks
  au!
  autocmd ColorScheme * hi Search ctermbg=15
  autocmd ColorScheme * hi SpellBad cterm=underline
  autocmd ColorScheme * hi VertSplit ctermbg=NONE
  autocmd ColorScheme * hi Visual ctermbg=white
augroup END

" Statusbar
set statusline=\ %f\  " Filename
set statusline+=%{fugitive#statusline()} " Git info

set statusline+=%= " Separator

set statusline+=%y " File type
set statusline+=[%{strlen(&fenc)?&fenc:'none'}] " File encoding
set statusline+=[%{&ff}] " File ending
set statusline+=\ %P\ of\ %L\  " Perc. file
set statusline+=(%l\:%c)\ " Line info

" Column ruler
set colorcolumn=120

" ##################
" Language Specifics
" ##################

let g:rustfmt_autosave = 1

let g:go_fmt_command = "goimports"
let g:go_fmt_autosave = 1

let g:scala_sort_across_groups = 1
let g:scala_scaladoc_indent = 1

let g:markdown_minlines = 100
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'ruby', 'scala', 'go']

autocmd BufNewFile,BufReadPost *.md set filetype=markdown
