dbus-update-activation-environment --systemd DISPLAY
/usr/bin/gnome-keyring-daemon &
export SSH_AUTH_SOCK

redshift &
slstatus &
~/.bin/random-gradient-wallpaper &
compton &
dunst -c ~/.config/dunst/dunstrc &
~/.bin/nextcloud &

xautolock -time 10 -locker slock &

while :; do
  ssh-agent dbus-run-session -- dwm &>> .dwm.log
done
