xset +fp /home/brennovich/.fonts
xset fp rehash

slstatus &
hsetroot -tile ~/.my-favorite-things/wallpaper.png &
compton &
dunst -c ~/.config/dunst/dunstrc &

xautolock -time 10 -locker slock &

exec dwm
