bindkey -v

bindkey ^R history-incremental-search-backward
bindkey ^S history-incremental-search-forward
bindkey ^P up-line-or-search
bindkey ^N down-line-or-search

for env in ~/.env-*; do
	. ${env}
done

export HISTFILESIZE=99999999 \
	HISTSIZE=99999999 \
	HISTFILE=~/.zsh_history \
	GPG_TTY=$(tty) \
	EDITOR=vi

alias l='ls -lha --color'

autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit && compinit

if type kubectl > /dev/null 2>&1; then source <(kubectl completion zsh); fi

setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS

if type nvim > /dev/null 2>&1; then alias vim='nvim'; fi
