#! /bin/sh

feh --bg-scale __my_favorite_things__/wallpapers/popload.jpg &
comptom --config ~/.comptom.conf &

bspc config border_width         8
bspc config window_gap          18

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI
