font_family Jetbrains Mono
font_size 18.0

cursor #6768aa
cursor_text_color #f6f4f0
cursor_beam_thickness 2

scrollback_lines 20000

mouse_hide_wait 3.0

url_color #6768aa

enable_audio_bell no

remember_window_size  yes
initial_window_width  640
initial_window_height 800
remember_window_position yes

resize_in_steps no

window_padding_width 15

hide_window_decorations titlebar-only

tab_bar_style separator
tab_separator " "
tab_title_template "○"
active_tab_title_template "●"
tab_bar_margin_height 10 -10
tab_bar_margin_width 15
tab_bar_edge bottom
tab_bar_align left
tab_bar_background none
active_tab_background #101010
active_tab_foreground #b9b9b9
inactive_tab_background #101010
inactive_tab_foreground #585858

allow_hyperlinks yes
shell_integration enabled

map command+t new_tab_with_cwd

allow_remote_control yes

include ~/.config/kitty/themes/marques-de-itu-dark.conf
