font_family Go Mono
font_size 15.0

cursor #6768aa
cursor_text_color #f6f4f0
cursor_beam_thickness 2

scrollback_lines 20000

mouse_hide_wait 3.0

url_color #6768aa

enable_audio_bell no

remember_window_size  yes
initial_window_width  640
initial_window_height 800
remember_window_position yes

resize_in_steps no

window_padding_width 15

hide_window_decorations titlebar-only

# tab_bar_edge top
# tab_bar_margin_width 0.0
# tab_bar_margin_height 0.0 0.0
tab_bar_style hidden
# tab_bar_filter
# tab_bar_align left
# tab_bar_min_tabs 2
# tab_switch_strategy previous
# tab_fade 0.25 0.5 0.75 1
# tab_separator " ┇"
# tab_powerline_style angled
# tab_activity_symbol none
# tab_title_max_length 0
# tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"

allow_hyperlinks yes
shell_integration enabled

map kitty_mod+enter new_window_with_cwd

allow_remote_control yes

include ~/.config/kitty/themes/marques-de-itu-dark.conf
