changequote(`[[[', `]]]')
export EDITOR=nvim
export PATH=$HOME/.bin:$PATH
export TERM=xterm
export HISTSIZE=20000

alias ls='ls --color'
alias vim='nvim'
alias nv='nvim'
alias grep='grep --color=auto --exclude-dir=.git --line-number --binary-files=without-match'
alias grepd='grep --color=auto --exclude-dir=.git --line-number --dereference-recursive --binary-files=without-match'

function __parse_git_status {
  index=`if [ -d .git ]; then git status -s | awk '{ print $1 }'; fi;`

  case "$index" in
    *'??'*)
      printf '¡'
      ;;
    *D*)
      printf '-'
      ;;
    *M*)
      printf '*'
      ;;
    *)
      ;;
  esac
}

export PS1="[\[\e[35m\]\W\[\e[m\]\[\e[0;37m\]\$(__parse_git_status)\[\e[m\]] "
changequote([[[`]]], [[[']]])
