changequote(`[[[', `]]]')

source ~/.config/base16-shell/scripts/base16-grayscale-light.sh

if [ -s ~/.env-golang ]; then
  source ~/.env-golang
fi

if [ -s ~/.env-rust ]; then
  source ~/.env-rust
fi

# enable bash completion in interactive shells
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export EDITOR=vim
export PATH=$HOME/.bin:/sbin:$PATH
export HISTSIZE=-1

alias ls='ls --color'
alias grepc='grep --color=auto --exclude-dir=.git --line-number --binary-files=without-match'
alias grepd='grep --color=auto --exclude-dir=.git --line-number --dereference-recursive --binary-files=without-match'
alias presentation-term='urxvt -fn "xft:Terminus:size=24:style=regular:antialias=false" -fb "xft:Terminus:size=24:style=Bold:antialias=false"'

function __parse_git_status {
  repo_check=$(git status &> /dev/null; echo $?)
  index=`if [ ${repo_check} -eq 0 ]; then git status -s | awk '{ print $1 }'; fi;`

  case "$index" in
    *'??'*)
      printf '¡'
      ;;
    *D*)
      printf '-'
      ;;
    *M*)
      printf '*'
      ;;
    *)
      ;;
  esac
}

export PS1="[\[\e[35m\]\W\[\e[m\]\[\e[0;37m\]\$(__parse_git_status)\[\e[m\]] "
export GPG_TTY=$(tty)

changequote([[[`]]], [[[']]])
