export _JAVA_AWT_WM_NONREPARENTING=1

xrdb -load ~/.Xresources
xsetroot -name my_favorite_things
xsetroot -cursor_name left_ptr
hsetroot -fill __my_favorite_things__/wallpapers/popload.jpg

panel &
compton &
redshift &

exec 2bwm
